[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_MODULES_CACHE = "false"
  # Enable Corepack so pnpm/yarn are available
  COREPACK_ENABLE_DOWNLOADS = "1"
  # ensure pnpm is installed
  PNPM_VERSION = "9.12.1"

